comment: off

coverage:
  status:
    project:
      default:
        target: 90%
        threshold: 2%
        base: auto
  range: 90..100
  round: down
  precision: 2

ignore:
  - "**/com.kosinskyi.ecom.registry.ApplicationStarter.java"