dist:
  trusty

language:
  java

jdk:
  - oraclejdk8

node_js:
  - "10"

cache:
  directories:
    - $HOME/.m2
    - frontend/node_modules/
before_script:
  - npm install --prefix frontend/

script:
  - mvn clean package sonar:sonar
  - npm run build --prefix frontend/
after_success:
  - bash <(curl -s https://codecov.io/bash)

addons:
  sonarcloud:
    organization: "skosinskiy-github"
    token: "${SONAR_TOKEN}"