dist:
  trusty

language:
  java

jdk:
  - oraclejdk8

node_js:
  - "10"

cache:
  directories:
    - $HOME/.m2

script:
  - mvn clean package
  - sonar-scanner
after_success:
  - bash <(curl -s https://codecov.io/bash)

addons:
  sonarcloud:
    organization: "skosinskiy-github"
    token:
      secure: ${SONAR_TOKEN}