version: "3.4"

services:
  parser:
    container_name: parser
    env_file:
      - ./registry.env
    build:
      context: ./
    depends_on:
      - db
    entrypoint: "java -Djava.security.egd=file:/dev/./urandom -jar app.jar --spring.profiles.active=docker"
    volumes:
      - ./storage:/storage
      - ./logs:/logs
    ports:
    - '80:10000'

  db:
    container_name: parser-db
    image: postgres:12.2-alpine
    environment:
      POSTGRES_DB: "parser"
      POSTGRES_USER: "parser"
      POSTGRES_PASSWORD: "parser"
      PGDATA: /data/postgres
    ports:
      - '5430:5432'
    volumes:
     - parser-db-v:/data/postgres

volumes:
  parser-db-v: