spring:
  datasource:
    url:
      jdbc:h2:mem:ecom-registry;DB_CLOSE_ON_EXIT=FALSE
    username:
      sa
server:
  port:
    10000

app:
  jwtSecret:
    ${random.uuid}
  jwtRefreshTokenExpirationInMs:
    120000
  jwtAccessTokenExpirationInMs:
    75000