spring:
  datasource:
    url:
      jdbc:h2:mem:ecom-registry;DB_CLOSE_ON_EXIT=FALSE
    username:
      sa
server:
  port:
    10000

app:
  jwtSecret:
    ${random.uuid}
  jwtRefreshTokenExpirationInMs:
    1209600000
  jwtAccessTokenExpirationInMs:
    900000

aws:
  s3:
    credentials:
      path:
        src/main/resources/aws/s3/credentials