export const DAILY_REGISTRY_PARSE_CRITERIA_LOADING = 'DAILY_REGISTRY_PARSE_CRITERIA_LOADING'
export const DAILY_REGISTRY_PARSE_CRITERIA_FETCHED = 'DAILY_REGISTRY_PARSE_CRITERIA_FETCHED'
export const PAGE_UPDATED = 'PAGE_UPDATED'