drop table if exists daily_registry;
drop table if exists daily_registry_parse_criteria;
drop table if exists daily_registry_parse_criteria_filter_value;
drop table if exists file_item;
drop table if exists user_permissions;
drop table if exists users;

create table daily_registry
(
    id                      bigint generated by default as identity,
    date_created            timestamp,
    date_modified           timestamp,
    registry_date           date,
    status                  varchar(255) not null,
    parsed_registry_item_id bigint,
    registry_item_id        bigint       not null,
    user_id                 bigint,
    primary key (id)
);

create table daily_registry_parse_criteria
(
    id                 bigint generated by default as identity,
    date_created       timestamp,
    date_modified      timestamp,
    filter_column_name varchar(255) not null,
    name               varchar(255) not null,
    primary key (id)
);

create table daily_registry_parse_criteria_filter_value
(
    criteria_id bigint not null,
    value       varchar(255)
);

create table file_item
(
    id            bigint generated by default as identity,
    date_created  timestamp,
    date_modified timestamp,
    extension     varchar(255) not null,
    key           varchar(255) not null,
    size          bigint,
    primary key (id)
);

create table user_permissions
(
    user_id       bigint not null,
    permission_id integer
);

create table users
(
    id                            bigint generated by default as identity,
    date_created                  timestamp,
    date_modified                 timestamp,
    account_expire_date           timestamp,
    email                         varchar(255),
    first_name                    varchar(255),
    jwt_refresh_token             varchar(255),
    jwt_refresh_token_expire_date timestamp,
    last_name                     varchar(255),
    password                      varchar(255),
    role_id                       varchar(255),
    primary key (id)
);

alter table daily_registry
    add constraint UK_fcgmw5451rubd2ky0bu0itq5s unique (registry_date);
alter table daily_registry_parse_criteria
    add constraint UK_mar0v47xp4nyfj2tmjpww8m0o unique (name);
alter table daily_registry_parse_criteria_filter_value
    add constraint UKpa597q8uer2h2rj3jm7i0xl6i unique (criteria_id, value);
alter table file_item
    add constraint UK_nu5ybewaijqve7ab503u1su7t unique (key);
alter table daily_registry
    add constraint FKoxlk58xg84a49krfy6lnlybys foreign key (parsed_registry_item_id) references file_item;
alter table daily_registry
    add constraint FK3afn3st7igksrpuipaipgo1kq foreign key (registry_item_id) references file_item;
alter table daily_registry
    add constraint FK7jlfld8alckpibcussm9o6s54 foreign key (user_id) references users;
alter table daily_registry_parse_criteria_filter_value
    add constraint FKn8ffjch3s5vgl67njpdm5fedp foreign key (criteria_id) references daily_registry_parse_criteria;
alter table user_permissions
    add constraint FKkowxl8b2bngrxd1gafh13005u foreign key (user_id) references users;